---
language: node_js
node_js:
  - "8"

sudo: false

dist: trusty

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

env:
  # we recommend testing LTS's and latest stable release (bonus points to beta/canary)
  - EMBER_TRY_SCENARIO=ember-3.4.0
  - EMBER_TRY_SCENARIO=ember-3.5.0
  - EMBER_TRY_SCENARIO=ember-3.6.0
  - EMBER_TRY_SCENARIO=ember-3.7.0
  - EMBER_TRY_SCENARIO=ember-3.8.0

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-3.8.0

before_install:
  - npm config set spin false

install:
  - npm install

script:
script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
